#ifndef LEAPEMU_CPU_REGISTERS_H
#define LEAPEMU_CPU_REGISTERS_H

/* Core Register Set */
enum ARC_CORE_REGS {
    /* General Purpose Registers */
    ARC_REG_R0, ARC_REG_R1, ARC_REG_R2, ARC_REG_R3,
    ARC_REG_R4, ARC_REG_R5, ARC_REG_R6, ARC_REG_R7,
    ARC_REG_R8, ARC_REG_R9, ARC_REG_R10, ARC_REG_R11,
    ARC_REG_R12, ARC_REG_R13, ARC_REG_R14, ARC_REG_R15,
    ARC_REG_R16, ARC_REG_R17, ARC_REG_R18, ARC_REG_R19,
    ARC_REG_R20, ARC_REG_R21, ARC_REG_R22, ARC_REG_R23,
    ARC_REG_R24, ARC_REG_R25,
    /* Pointer Registers */
    ARC_REG_GP, ARC_REG_FP, ARC_REG_SP,
    /* Link Registers */
    ARC_REG_ILINK1, ARC_REG_ILINK2, ARC_REG_BLINK,
    /* Extension Registers */
    ARC_REG_R32, ARC_REG_R33, ARC_REG_R34, ARC_REG_R35,
    ARC_REG_R36, ARC_REG_R37, ARC_REG_R38, ARC_REG_R39,
    ARC_REG_R40, ARC_REG_R41, ARC_REG_R42, ARC_REG_R43,
    ARC_REG_R44, ARC_REG_R45, ARC_REG_R46, ARC_REG_R47,
    ARC_REG_R48, ARC_REG_R49, ARC_REG_R50, ARC_REG_R51,
    ARC_REG_R52, ARC_REG_R53, ARC_REG_R54, ARC_REG_R55,
    ARC_REG_R56, ARC_REG_R57, ARC_REG_R58, ARC_REG_R59,
    /* Other Registers */
    ARC_REG_LP_COUNT, ARC_REG_RESERVED, ARC_REG_LONG_IMM, ARC_REG_PCL
};

/* Multiply Core Registers */
#define ARC_REG_MLO ARC_REG_R57
#define ARC_REG_MMID ARC_REG_R58
#define ARC_REG_MHI ARC_REG_R59

/* XY Memory Core Registers */
#define ARC_REG_X0_U0 ARC_REG_R32
#define ARC_REG_X0_U1 ARC_REG_R33
#define ARC_REG_X1_U0 ARC_REG_R34
#define ARC_REG_X1_U1 ARC_REG_R35
#define ARC_REG_X2_U0 ARC_REG_R36
#define ARC_REG_X2_U1 ARC_REG_R37
#define ARC_REG_X3_U0 ARC_REG_R38
#define ARC_REG_X3_U1 ARC_REG_R39
#define ARC_REG_Y0_U0 ARC_REG_R40
#define ARC_REG_Y0_U1 ARC_REG_R41
#define ARC_REG_Y1_U0 ARC_REG_R42
#define ARC_REG_Y1_U1 ARC_REG_R43
#define ARC_REG_Y2_U0 ARC_REG_R44
#define ARC_REG_Y2_U1 ARC_REG_R45
#define ARC_REG_Y3_U0 ARC_REG_R46
#define ARC_REG_Y3_U1 ARC_REG_R47
#define ARC_REG_X0_NU ARC_REG_R48
#define ARC_REG_X1_NU ARC_REG_R49
#define ARC_REG_X2_NU ARC_REG_R50
#define ARC_REG_X3_NU ARC_REG_R51
#define ARC_REG_Y0_NU ARC_REG_R52
#define ARC_REG_Y1_NU ARC_REG_R53
#define ARC_REG_Y2_NU ARC_REG_R54
#define ARC_REG_Y3_NU ARC_REG_R55
#define ARC_REG_ACC0 ARC_REG_R56
#define ARC_REG_ACC1 ARC_REG_R57

/* XMAC Core Registers */
#define ARC_REG_XMAC0 ARC_REG_R42
#define ARC_REG_XMAC1 ARC_REG_R43

/* Auxiliary Register Set */
enum ARC_AUX_REGS {
    ARC_REG_STATUS,
    ARC_REG_SEMAPHORE,
    ARC_REG_LP_START,
    ARC_REG_LP_END,
    ARC_REG_IDENTITY,
    ARC_REG_DEBUG,
    ARC_REG_PC32,
    ARC_REG_STATUS32 = 0x0a,
    ARC_REG_STATUS32_L1,
    ARC_REG_STATUS32_L2,
    ARC_REG_IC_IVIC = 0x10,
    ARC_REG_IC_CTRL,
    ARC_REG_MULHI,
    ARC_REG_IC_LIL,
    ARC_REG_IC_IVIL = 0x19,
    ARC_REG_IC_RAM_ADDR,
    ARC_REG_IC_TAG,
    ARC_REG_IC_WP,
    ARC_REG_IC_DATA,
    ARC_REG_SRAM_SEQ = 0x20,
    ARC_REG_COUNT0,
    ARC_REG_CONTROL0,
    ARC_REG_LIMIT0,
    ARC_REG_PCPORT,
    ARC_REG_INT_VECTOR_BASE = 0x25,
    ARC_REG_AUX_MACMODE = 0x41,
    ARC_REG_AUX_LSP_NEWVAL,
    ARC_REG_AUX_IRQ_LV12,
    ARC_REG_AUX_XMAC0,
    ARC_REG_AUX_XMAC1,
    ARC_REG_AUX_XMAC2,
    ARC_REG_DC_IVDC,
    ARC_REG_DC_CTRL,
    ARC_REG_DC_LDL,
    ARC_REG_DC_IVDL,
    ARC_REG_DC_FLSH,
    ARC_REG_DC_FLDL,
    ARC_REG_DC_RAM_ADDR = 0x58,
    ARC_REG_DC_TAG,
    ARC_REG_DC_WP,
    ARC_REG_DC_DATA,
    /* Build Configuration Registers { */
    ARC_REG_VBFDW_BUILD = 0x64,
    ARC_REG_EXT_ARITH_BUILD,
    ARC_REG_DATASPACE,
    ARC_REG_MEMSUBSYS,
    ARC_REG_VECBASE_AC_BUILD,
    ARC_REG_P_BASE_ADDR,
    ARC_REG_D_CACHE_BUILD = 0x72,
    ARC_REG_MADI_BUILD,
    ARC_REG_LDSTRAM_BUILD,
    ARC_REG_TIMER_BUILD,
    ARC_REG_AP_BUILD,
    ARC_REG_I_CACHE_BUILD,
    ARC_REG_ADDSUB_BUILD,
    ARC_REG_DSPRAM_BUILD,
    ARC_REG_MAC_BUILD,
    ARC_REG_MULTIPLY_BUILD,
    ARC_REG_SWAP_BUILD,
    ARC_REG_NORM_BUILD,
    ARC_REG_MINMAX_BUILD,
    ARC_REG_BARREL_BUILD,
    /* } */
    ARC_REG_AX0,
    ARC_REG_AX1,
    ARC_REG_AX2,
    ARC_REG_AX3,
    ARC_REG_AY0,
    ARC_REG_AY1,
    ARC_REG_AY2,
    ARC_REG_AY3,
    ARC_REG_MX00,
    ARC_REG_MX01,
    ARC_REG_MX10,
    ARC_REG_MX11,
    ARC_REG_MX20,
    ARC_REG_MX21,
    ARC_REG_MX30,
    ARC_REG_MX31,
    ARC_REG_MY00,
    ARC_REG_MY01,
    ARC_REG_MY10,
    ARC_REG_MY11,
    ARC_REG_MY20,
    ARC_REG_MY21,
    ARC_REG_MY30,
    ARC_REG_MY31,
    ARC_REG_XYCONFIG,
    ARC_REG_BURSTSYS,
    ARC_REG_BURSTXYM,
    ARC_REG_BURSTSZ,
    ARC_REG_BURSTVAL,
    ARC_REG_COUNT1 = 0x100,
    ARC_REG_CONTROL1,
    ARC_REG_LIMIT1,
    ARC_REG_AUX_IRQ_LEV = 0x200,
    ARC_REG_AUX_IRQ_HINT
};

/* Note: Aux register data wraps around every 65536 registers. */
#define ARC_AUX_REG(x) (((x % 65536) >= 516) ? ARC_REG_IDENTITY : (x % 65536))

#endif
